@GameAuth_HostAddress = http://localhost:5074

### register
POST {{GameAuth_HostAddress}}/auth/register
Content-Type: application/json

{
  "username": "test",
  "email": "test@test.com",
  "password": "password123"
}

### verify-email
POST {{GameAuth_HostAddress}}/auth/verify-email
Content-Type: application/json

{
    "rawToken" : "amubTkTZTD-l9pm5XzBHZCgeKP471GSBOEopy7onL1s"
}

### login
POST {{GameAuth_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password123"
}
